yocosmos/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField 
from wtforms.validators import DataRequired, Length

class PostForm(FlaskForm):
    content = TextAreaField('', validators=[DataRequired(), Length(min=1, max=5000)])
    submit = SubmitField('Submit Post')

yocosmos/main/routes.py
from flask import render_template, request, Blueprint, jsonify, make_response, flash, redirect, url_for
from yocosmos import db, limiter
from yocosmos.models import Post, Liker
from yocosmos.main.forms import ContactForm
from yocosmos.main.utils import send_contact_email
from flask_limiter.util import get_remote_address
from sqlalchemy import func

import time
import json

main = Blueprint('main', __name__)


# @main.route("/")
# def home():
#posts = Post.query.all()

#    page = request.args.get('page', 1, type=int)
#    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
#    return render_template('home.html', posts=posts)


@main.route("/")
def home():
    #posts = Post.query.all()
    return render_template('home.html')


@main.route("/like/<int:id>", methods=["POST"])
@limiter.limit("1000/hour")
def like(id):
    address = get_remote_address()
    #print("HONK")
    likerquery = db.session.query(Liker).filter(Liker.ip_address == address, Liker.post_id == id).all()
    if(likerquery != []):
        return ""
    else:
        liker = Liker(ip_address=address, post_id=id)
        db.session.add(liker)
        db.session.commit()
        return ""
    

@main.route("/unlike/<int:id>", methods=["POST"])
@limiter.limit("1000/hour")
def unlike(id):
    address = get_remote_address()
    #print("DIMANCHE")
    likerquery = db.session.query(Liker).filter(Liker.ip_address == address, Liker.post_id == id).all()
    if(likerquery == []):
        return ""
    else:
        db.session.delete(likerquery[0])
        db.session.commit()
    return ""


@main.route("/load")
def load():
    """ Route to return the posts """

    time.sleep(0.2)     # Used to simulate delay
    quantity = 10       # Number of posts to return at a time
    postcount = Post.query.order_by(Post.date_posted.desc()).first().id

    if request.args:
        # The 'counter' value sent in the QS
        pagecounter = int(request.args.get("c"))

        if pagecounter == 0:
            print(f"Returning page {pagecounter}")
            posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=1, per_page=10).items
            data = {'posts': [], 'likes': []}
            for c in posts:
                data['likes'].append(len(c.likers))
                data['posts'].append(json.dumps(c.to_dict()))
            # print(json.dumps(data))
            res = make_response(json.dumps(data), 200)

        elif (pagecounter * 10) >= postcount:
            print("No more posts")
            res = make_response(jsonify({}), 200)

        else:
            print(f"Returning page {pagecounter}")
            posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=(pagecounter+1), per_page=10).items
            # insert here = get like counts for these 10 posts and send in the data
            # make a new data = {'posts': []; 'likes': []} or something like that
            data = {'posts': [], 'likes': []}
            for c in posts:
                data['likes'].append(len(c.likers))
                data['posts'].append(json.dumps(c.to_dict()))
            # print(json.dumps(data))
            res = make_response(json.dumps(data), 200)

        return res
    else:
        return


@main.route("/about")
def about():
    return render_template('about.html')


@main.route("/privacy_policy")
def privacy_policy():
    return render_template('privacy-policy.html')


@main.route("/terms_of_service")
def terms_of_service():
    return render_template('terms-of-service.html')

# @main.route("/contact")
# def contact():
#    return render_template('contact.html')


@main.route("/contact", methods=['POST'])
@limiter.limit("5/hour")
@limiter.limit("20/day")
def contact_post():
    form = ContactForm()
    if form.validate_on_submit():
        send_contact_email(form.name.data, form.email.data, form.content.data)
        flash(f'Your message has been sent to the website administrators.', 'success')
        return redirect(url_for('main.home'))
    flash(f'There was an error sending your message. Please check your formatting and try again.', 'danger')
    return render_template('contact.html', title='Contact Form', form=form, legend='Contact Form')


@main.route("/contact", methods=['GET'])
def contact_get():
    form = ContactForm()
    return render_template('contact.html', title='Contact Form', form=form, legend='Contact Form')

yocosmos/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request
from yocosmos import db, limiter
from yocosmos.posts.forms import PostForm
from yocosmos.models import Post
from flask_limiter.util import get_remote_address
import os
import random

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['POST'])
@limiter.limit("500/day")
@limiter.limit("50/hour")
@limiter.limit("5/minute")
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        address = get_remote_address()

        # get the directory of the current script
        script_dir = os.path.dirname(os.path.realpath(__file__))

        # create the absolute path of the avatar images directory
        avatars_dir = os.path.join(script_dir, '../static/avatars')

        # get list of avatar images
        avatar_images = os.listdir(avatars_dir)

        # randomly select an avatar
        selected_avatar = random.choice(avatar_images)

        post = Post(content=form.content.data, user_ip=address, avatar_image=selected_avatar)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been submitted!', 'success')
        return redirect(url_for('main.home'))
    return new_post_get()



@posts.route("/post/new", methods=['GET'])
def new_post_get():
    form = PostForm()
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post, likes=len(post.likers))

yocosmos/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="about_section">
    <h1 class="has-darkmode darkmode">About Page</h1>
    <p class="has-darkmode darkmode">
        Welcome to Yo Cosmos
    </p>

    <p class="has-darkmode darkmode">
        Yo Cosmos is an alternative to traditional social media platforms.
    </p>

    <p class="has-darkmode darkmode">
        On Yo Cosmos there are no accounts, no usernames, no profiles, and no images. Any user can yeet their thoughts
        out into the cosmos as often as they choose (within reasonable rate limits).
    </p>

    <h3 class="has-darkmode darkmode">What is Yo Cosmos?</h3>
    <p class="has-darkmode darkmode">
        Have something to say, but no one to say it to? Want something to be known to the universe?
    </p>

    <p class="has-darkmode darkmode">
        Yo Cosmos is the perfect place to hurl your thoughts, coherent or otherwise, into the
        Cosmos. (Who knows, maybe you'll hear back...)
    </p>





    <h3 class="has-darkmode darkmode">Cosmos Code of Conduct</h3>
    <p class="has-darkmode darkmode">
        Yo Cosmos is a text-only message board.

        We have rules of conduct that all users must obey at all times. By using this website, you agree to abide by the
        rules and terms set forth on this page, in our <a href="{{url_for('main.terms_of_service')}}">Terms of
            Service</a>, and in our <a href="{{url_for('main.privacy_policy')}}">Privacy Policy</a>.
    </p>
    <p>
        We reserve the right to change or modify these rules at any time without prior notice or reason.
    </p>
    <h3 class="has-darkmode darkmode">Rules</h3>
    <ol class="has-darkmode darkmode">
        <li>Don't post excessively inappropriate content</li>
        <p class="rule-subtext">Any posts containing content deemed excessively inappropriate by the site administrators
            (including self
            censored, automatically censored, acronyms and slang) will be removed from the forum at the discretion of
            the administrators. Posts containing pornography or illegal content will be removed and the user's ip
            adderss banned.</p>
        <li>Be tolerant</li>
        <p class="rule-subtext">Racial, sexual, or any other form of discrimination is not tolerated. Posts that contain
            discriminatory
            content will be removed at the discretion of the site administrators.</p>
        <li>Don't doxx anyone (including yourself)</li>
        <p class="rule-subtext">Don't post personally identifiable information (i.e. name, address, email, phone number,
            etc.), without
            explicit prior consent of all parties involved. Personally identifiable information that is posted with
            clear malicious intent will be removed by the administrators.</p>
        <li>Don't advertise</li>
        <p class="rule-subtext">Do not use Yo Cosmos to generate traffic or attention for your endeavor, links to
            personal websites and
            projects are permitted within reason as determined by the site administrators. Commercial activities of any
            kind are not permitted on Yo Cosmos. Any exception to these rules must be pre-authorised on a case by case
            basis by an administrator.</p>
        <li>Don't behave in a malicious manner</li>
        <p class="rule-subtext">
            Do not behave in a manner that can cause distress, harm or inconvenience to other members, staff or the site
            itself. This includes, but is not limited to, discrimination, bullying, offensive material, and breaching
            others privacy.
        </p>
        <li>Don't engage in illegal activity</li>
        <p class="rule-subtext">Yocosmos.com is located in the United States, and as such, United States law must be
            followed at all times.
            This includes Copyright law and Computer Misuse law (Malware, Virus etc).</p>
        <li>Reporting content</li>
        <p class="rule-subtext">Please do not make posts to inform other users of site rules or attempt to enforce rules
            without the
            authorization of site administrators. Use the <a href="{{url_for('main.contact_get')}}">Contact</a> link at
            the bottom of the page to inform
            administrators when a post breaks the website rules or when administrator attention is needed.</p>
        </ul>


</div>
{% endblock content %}

yocosmos/templates/contact.html
{% extends "layout.html" %}
{% block content %}
<div class="contact has-darkmode darkmode">
    <div class="contact-form-wrapper flex-ai-c flex-jc-c has-darkmode darkmode">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset>
                <legend class="">{{ legend }}</legend>
                <div class="form-item">
                    {{ form.name(class="has-darkmode darkmode") }}
                    {{ form.name.label(class="has-darkmode darkmode") }}
                    {% if form.name.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors%}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-item">
                    {{ form.email(class="has-darkmode darkmode") }}
                    {{ form.email.label(class="has-darkmode darkmode") }}
                    {% if form.email.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors%}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>

                <div class="form-item">
                    {{ form.content(class="has-darkmode darkmode") }}
                    {{ form.content.label(class="has-darkmode darkmode") }}
                    {% if form.content.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors%}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </fieldset>

            <br>
            <button type="submit">Send Message</button>
        </form>
    </div>
</div>

{% endblock content %}

yocosmos/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="create-post has-darkmode darkmode">
    <div class="create-post-form-wrapper flex-ai-c flex-jc-c has-darkmode darkmode">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="">
                <legend class="">{{ legend }}</legend>
                <div class="post-input">
                    {{ form.content.label(class="has-darkmode darkmode") }}

                    {% if form.content.errors %}
                    {{ form.content(class="is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors%}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.content(class="has-darkmode darkmode") }}
                    {% endif %}
                </div>
                <div class="accept-terms-area">
                    <input type="checkbox" name="accept_terms" required />
                    <label for="accept_terms" id="accept-terms">I have read and agree to the <a
                            href="{{url_for('main.terms_of_service')}}">Terms of Service</a>. <br>I understand that I
                        cannot edit my post in any way once it is submitted.</label>
                </div>
            </fieldset>
            <br>
            <button type="submit">Submit</button>
        </form>
    </div>
</div>


{% endblock content %}

yocosmos/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div>
    <div class="flex flex-jc-c flex-ai-c">

        <button class="button flex flex-jc-c flex-ai-c has-darkmode darkmode" id="postButton"
            onclick="window.location.href=`{{url_for('posts.new_post_get')}}`;">POST</button>

    </div>
    <div id="scroller">
        <template id="post_template">
            <div id="content_section_area" class="content_section has-darkmode darkmode">
                <div class="post flex">
                    <div id="post_precontent_area" class="post__precontent flex flex-ai-c has-darkmode darkmode">
                        <div class="">
                            <img class="post__img" id="post_img"
                                src="{{ url_for('static', filename='avatars/0.png')}}">
                        </div>
                        <div class="post__metadata">
                            <p id="post_date"></p>
                            <p id="post_time"></p>
                            <p id="post_id"></p>
                        </div>
                    </div>
                    <div id="post_content_area" class="post__content has-darkmode darkmode flex flex-ai-c">
                        <p id="post_content"></p>
                        <div class="likes flex flex-ai-c flex-jc-sb">
                            <span id="post_likecount">0</span>
                            <svg id="heart" class="like-button" title="heart-unfilled" width="21" height="21"
                                viewBox="0 0 24 24" fill="none" stroke="#A9A9A9" stroke-width="2.5"
                                stroke-linecap="round" stroke-linejoin="round">
                                <path
                                    d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                                </path>
                            </svg>
                        </div>
                    </div>
                </div>
            </div>
        </template>
    </div>
    <!-- element to trigger the IntersectionObserver -->
    <div class="flex flex-jc-c" id="sentinel">
        <div class="loader has-darkmode darkmode">
            <div class="spinner flex flex-jc-c flex-ai-c has-darkmode darkmode" aria-hidden="true"></div>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='js/likes.js')}}"></script>
<script src="{{ url_for('static', filename='js/scroll.js')}}"></script>



{% endblock content %}

yocosmos/templates/layout.html
<!DOCTYPE html>
<html>

<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-5FYSV2R37Q"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-5FYSV2R37Q');
  </script>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')}}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Rubik&display=swap" rel="stylesheet">

  {% if title %}
  <title>yocosmos.com - {{ title }}</title>
  {% else %}
  <title>YO COSMOS</title>
  {% endif %}
</head>



<body class="has-darkmode darkmode">

  <header class="header">
    <div class="overlay has-fade"></div>
    <nav class="flex flex-jc-sb flex-ai-c container">
      <a href="/" class="header__logo has-darkmode darkmode">
        <p>YO COSMOS</p>
        <!-- <img src="images/logo.png" alt="Logo Image"> -->
      </a>

      <div class="header__links flex flex-jc-sb flex-ai-c has-darkmode darkmode">
        <!-- <a class="" href="{{url_for('main.about')}}">About</a> -->
        <button class="button flex flex-jc-c flex-ai-c has-darkmode darkmode" id="infoButton"
          onclick="window.location.href=`{{url_for('main.about')}}`;">
          <img id="info_icon" src="{{ url_for('static', filename='images/questionmark.svg')}}" alt="help">
          <div class="hovershow">INFO</div>
        </button>
        <button class="button flex flex-jc-c flex-ai-c has-darkmode darkmode" id="modeButton">
          <img id="sun_icon" src="{{ url_for('static', filename='images/sun.svg')}}" alt="mode">
          <div class="hovershow">MODE</div>
        </button>
        <button class="button flex flex-jc-c flex-ai-c has-darkmode darkmode" id="starButton">
          <img id="stars_icon" src="{{ url_for('static', filename='images/stars.svg')}}" alt="starfield">
          <div class="hovershow">STARS</div>
        </button>
      </div>
    </nav>
  </header>


  <main role="main" class="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </main>

  <div class="footer">

    <div class="footer__links has-darkmode darkmode">

      <a href="{{url_for('main.privacy_policy')}}">Privacy Policy</a>
      <a href="{{url_for('main.contact_get')}}">Contact</a>
      <a href="{{url_for('main.terms_of_service')}}">Terms of Service</a>
    </div>

    <div class="footer__copyright has-darkmode darkmode">
      &copy; CS27 All Rights Reserved.
    </div>

  </div>

  <div id="cookiePopup" class="hide">
    <img src="{{ url_for('static', filename='images/cookie.png')}}" />
    <p>
      This website uses minimal cookies to enhance the browsing experience. By continuing to use this website, you agree
      to
      their use (outlined <a href="{{url_for('main.privacy_policy')}}">here</a>).
    </p>
    <button id="acceptCookie">Accept</button>
  </div>
  <div id="cookiePopupOverlay" class="hide"></div>

  </div>
  <div class="secretmenu has-darkmode darkmode">
    <a href="https://www.youtube.com/watch?v=fxqfGpxET38" target="_blank" rel="noopener noreferrer"><img id="yo"
        src="{{ url_for('static', filename='images/video.svg')}}" alt="yo"></a>
    <a href="https://ko-fi.com/coffeeswirl27" target="_blank" rel="noopener noreferrer"><img id="kofi"
        src="{{ url_for('static', filename='images/mug.svg')}}" alt="kofi"></a>
  </div>

  <div class="bg-animation">
    <div id="stars"></div>
    <div id="stars2"></div>
    <div id="stars3"></div>
    <div id="stars4"></div>
  </div>

  <script src="{{ url_for('static', filename='js/cookie.js')}}"></script>
  <script src="{{ url_for('static', filename='js/buttons.js')}}"></script>
  <script src="https://unpkg.com/htmx.org@1.8.4"></script>


</body>

</html>

yocosmos/templates/post.html
{% extends "layout.html" %}
{% block content %}

<div id="content_section_area" class="content_section has-darkmode darkmode">
    <div class="post flex">
        <div id="post_precontent_area" class="post__precontent flex flex-ai-c has-darkmode darkmode">
            <div class="">
                <img class="post__img" id="post_img" src="{{ url_for('static', filename='avatars/0.png')}}">
            </div>
            <div class="post__metadata">
                <p id="post_date">{{ post.date_posted.strftime('%Y-%m-%d') }}</p>
                <p id="post_time">{{ post.date_posted.strftime('%I:%M%p') }}</p>
                <p id="post_id"><a href="{{ url_for('posts.post', post_id=post.id) }}">#{{ post.id }}</a></p>
            </div>
        </div>
        <div id="post_content_area" class="post__content has-darkmode darkmode flex flex-ai-c">
            <p id="post_content">{{ post.content }}</p>
            <div class="likes flex flex-ai-c flex-jc-sb">
                <span id="post_likecount">{{ likes }}</span>
                <svg id="heart" class="like-button" title="heart-unfilled" width="21" height="21" viewBox="0 0 24 24"
                    fill="none" stroke="#A9A9A9" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
                    <path
                        d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z">
                    </path>
                </svg>
            </div>
        </div>
        
    </div>
</div>

<script src="{{ url_for('static', filename='js/likes.js')}}"></script>
<script src="{{ url_for('static', filename='js/post.js')}}"></script>


{% endblock content %}